apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo
  labels:
    app: demo
    test2: b

spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        test1: a
    spec:
      containers:
        - name: demo
          image: marloto/simple-express-js:v1.3
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "100Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

